name: challenge

on: [push, pull_request]

jobs:
  run-on-ubuntu:
    name: Print Date in ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - run: date
  run-on-macos:
    name: Print Date in ubuntu-latest
    runs-on: macos-latest
    steps:
      -  run: date
  run-on-ubuntu-third-time:
    name: Print Date in ubuntu-latest again
    needs: [run-on-ubuntu, run-on-macos]
    runs-on: ubuntu-latest
    steps:
      -  run: date